/* =====================================================================
   AHW Quizverse build tool
   1) Extracts the existing Q_* banks embedded in index.html (if still present)
   2) Merges them with data-new/part*.json (if present)
   3) Writes data/mcqs.json  (single source of truth — ALL subjects' MCQs)
   4) Writes data/mcqs.js   (mirror loaded via <script> so the site also
                            works when opened directly as an HTML file)
   Usage:  node tools/build.js
   ===================================================================== */
const fs = require("fs");
const path = require("path");
const ROOT = path.join(__dirname, "..");

function read(p) { return fs.readFileSync(path.join(ROOT, p), "utf8"); }

/* ---------- 1) existing embedded banks ---------- */
let existing = {};
const html = read("index.html");
const mScript = html.match(/<script>([\s\S]*?)<\/script>/);
if (mScript) {
  const js = mScript[1];
  const dStart = js.indexOf("/* ===== Q format");
  const rStart = js.indexOf("const QREG");
  if (dStart >= 0 && rStart > dStart) {
    const dataCode = js.slice(dStart, rStart);
    const names = [...dataCode.matchAll(/^const (Q_[A-Z0-9_]+)\s*=/gm)].map(m => m[1]);
    if (names.length) {
      const fn = new Function(dataCode + "\nreturn {" + names.map(n => n + ":" + n).join(",") + "};");
      existing = fn();
      console.log("extracted embedded banks:", names.length);
    }
  }
}

/* ---------- 2) merge current json + new parts ---------- */
let merged = {};
try { merged = JSON.parse(read("data/mcqs.json")); console.log("loaded existing mcqs.json banks:", Object.keys(merged).length); } catch (e) { /* first build */ }
Object.assign(merged, existing);
const dn = path.join(ROOT, "data-new");
if (fs.existsSync(dn)) {
  for (const f of fs.readdirSync(dn).filter(f => f.endsWith(".json")).sort()) {
    const part = JSON.parse(read("data-new/" + f));
    Object.assign(merged, part);
    console.log("merged", f, "banks:", Object.keys(part).length);
  }
}

/* ---------- 3) validate ---------- */
let q = 0;
for (const [k, bank] of Object.entries(merged)) {
  if (!bank.lv || !bank.lv.length) throw new Error(k + " has no levels");
  for (const L of bank.lv) {
    for (const entry of L.questions) {
      const [txt, opts, ci, why] = entry;
      if (typeof ci !== "number" || ci < 0 || ci >= opts.length) throw new Error(k + " bad index: " + txt.slice(0, 40));
      if (!why) throw new Error(k + " missing why: " + txt.slice(0, 40));
      q++;
    }
  }
}
console.log("total banks:", Object.keys(merged).length, "| total questions:", q);

/* ---------- 4) write outputs ---------- */
const compact = JSON.stringify(merged);
fs.writeFileSync(path.join(ROOT, "data/mcqs.json"), compact);
fs.writeFileSync(path.join(ROOT, "data/mcqs.js"), "/* AUTO-GENERATED by tools/build.js — edit data/mcqs.json and re-run build instead. */\nwindow.MCQS=" + compact + ";\n");
console.log("wrote data/mcqs.json (" + (compact.length / 1024).toFixed(0) + " KB) and data/mcqs.js");
