#!/usr/bin/env python3
"""
MCQ data cleaner — page-refs ko option text se hata kar explanation me le jata hai.
Usage: python3 tools/clean-mcqs.py [--root=.]
"""
import json, re, sys, os
root = next((a.split("=",1)[1] for a in sys.argv[1:] if a.startswith("--root=")), ".")
p = os.path.join(root, "data", "mcqs.json")
db = json.load(open(p, encoding="utf8"))
PAGE_IN_OPT = re.compile(r"\s*[\(\[]?\s*(?:page|p|pg)\.?\s*(\d{1,4})\s*[\)\]]?\s*$", re.I)
BARE_PAGE = re.compile(r"^\s*[\(\[]?\s*(?:page|p|pg)\.?\s*(\d{1,4})\s*[\)\]]?\s*$", re.I)
stats = {"opt_ref": 0, "why_upgraded": 0, "empty_why": 0, "trim": 0}
for key, bank in db.items():
    for L in bank["lv"]:
        for q in L["questions"]:
            text, opts, ans, why = q[0], q[1], q[2], q[3]
            # 1) option text se page ref nikal kar why me daalo
            refs = []
            for i, o in enumerate(opts):
                m = PAGE_IN_OPT.search(o)
                if m and len(o) > len(m.group(0)) + 1:
                    opts[i] = o[:m.start()].strip()
                    refs.append(m.group(1)); stats["opt_ref"] += 1
            why = (why or "").strip()
            # 2) why sirf "Page 21" ho to poora jumla banao
            m = BARE_PAGE.match(why)
            if m:
                why = f"Sahi jawab: {opts[ans]}. (VU handout — Page {m.group(1)})"
                stats["why_upgraded"] += 1
            elif refs and len(why) < 40:
                why = f"{why + ' — ' if why else ''}Reference: Page {refs[-1]}."
            # 3) khaali why
            if not why:
                why = f"Sahi jawab: {opts[ans]}. (VU past paper se — tafseel update honi hai.)"
                stats["empty_why"] += 1
            q[0] = re.sub(r"\s{2,}", " ", text).strip()
            q[3] = why
            if q[0] != text: stats["trim"] += 1
json.dump(db, open(p, "w", encoding="utf8"), ensure_ascii=False, separators=(",", ":"))
js = "/* AUTO-GENERATED by tools/build.js — edit data/mcqs.json and re-run build instead. */\nwindow.MCQS=" + json.dumps(db, ensure_ascii=False, separators=(",", ":")) + ";\n"
open(os.path.join(root, "data", "mcqs.js"), "w", encoding="utf8").write(js)
print("cleaned:", json.dumps(stats))
print("total questions:", sum(len(L["questions"]) for b in db.values() for L in b["lv"]))
